In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.read_json("https://raw.githubusercontent.com/siftech/SciClaim/main/PubMed/train_pos_pubmed_238.json")
df2 = pd.read_json("https://raw.githubusercontent.com/siftech/SciClaim/main/PubMed/val_pos_pubmed_23.json")
df3 = pd.read_json("https://raw.githubusercontent.com/siftech/SciClaim/main/PubMed/train_neg_pubmed_46.json")
df4 = pd.read_json("https://raw.githubusercontent.com/siftech/SciClaim/main/PubMed/val_neg_pubmed_4.json")
df5 = pd.read_json("https://raw.githubusercontent.com/siftech/SciClaim/main/PubMed/test_pubmed_100.json")
df6 = pd.read_json("https://raw.githubusercontent.com/siftech/SciClaim/main/additonal/manual_perturbations_19.json")
df7 = pd.read_json("https://raw.githubusercontent.com/siftech/SciClaim/main/CORD-19/train_pos_cord_117.json")
df8 = pd.read_json("https://raw.githubusercontent.com/siftech/SciClaim/main/CORD-19/val_pos_cord_18.json")

In [3]:
df = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8])

In [4]:
df.drop(columns = ['uuid', 'notes', 'modified', 'dataset', 'relations', 'attributes', 'user'], inplace = True)

In [5]:
df

,text,tokens,entities,created
0,"the number of comorbidities, the Rockall scale...","[the, number, of, comorbidities, ,, the, Rocka...","[{'start': 0, 'end': 4, 'type': 'factor'}, {'s...",NaN
1,The BDI is a significant predictor of long-ter...,"[The, BDI, is, a, significant, predictor, of, ...","[{'start': 0, 'end': 2, 'type': 'factor'}, {'s...",NaN
2,The application of 1% MBD as a single techniqu...,"[The, application, of, 1, %, MBD, as, a, singl...","[{'start': 15, 'end': 21, 'type': 'factor'}, {...",NaN
3,Risks of CVD events and mortality increased ex...,"[Risks, of, CVD, events, and, mortality, incre...","[{'start': 0, 'end': 4, 'type': 'factor'}, {'s...",NaN
4,This study has found that inappropriate infant...,"[This, study, has, found, that, inappropriate,...","[{'start': 0, 'end': 2, 'type': 'evidence'}, {...",NaN
...,...,...,...,...
13,NaN,"[Most, patients, with, confirmed, or, suspecte...","[{'start': 8, 'end': 10, 'type': 'association'...",NaN
14,NaN,"[The, relatively, small, proportion, of, curre...","[{'start': 0, 'end': 13, 'type': 'factor'}, {'...",NaN
15,NaN,"[The, elderly, and, people, with, underlying, ...","[{'start': 0, 'end': 2, 'type': 'factor'}, {'s...",NaN
16,NaN,"[differences, in, COVID-19, disease, prevalenc...","[{'start': 6, 'end': 7, 'type': 'factor'}, {'s...",NaN
17,NaN,"[A, new, study, published, by, the, journal, A...","[{'start': 0, 'end': 3, 'type': 'evidence'}, {...",NaN

In [6]:
import nltk
def tag(tokens):
    tags = nltk.pos_tag(tokens)
    tags = [x[1] for x in tags]
    return tags

In [7]:
from ast import literal_eval as load

In [8]:
sentence_id = []
words = []
labels = []
pos_tag = []
for i in range(len(df)):
    tokens = df.iloc[i, 1]
    entities = df.iloc[i, 2]
    label = ['O']*len(tokens)
    sid = [i]*len(tokens)
    for entity in entities:
        x = entity['start']
        label[x] = 'B'
        x = x+1
        while(x<entity['end']):
            label[x] = 'I'
            x = x+1
    tags = tag(tokens)
    sentence_id.extend(sid)
    words.extend(tokens)
    labels.extend(label)
    pos_tag.extend(tags)

In [9]:
df_covid = pd.DataFrame({'sentence_id': sentence_id, 'words': words, 'labels': labels, 'pos_tag':pos_tag})

In [10]:
df_covid.to_csv("Dataset_TaskB/SciClaim.csv", index = None)

In [12]:
df_covid

       sentence_id          words labels pos_tag
0                0            the      B      DT
1                0         number      I      NN
2                0             of      I      IN
3                0  comorbidities      I     NNS
4                0              ,      O       ,
...            ...            ...    ...     ...
11943          564            228      I      CD
11944          564              ,      I       ,
11945          564           2020      I      CD
11946          564              )      O       )
11947          564              .      O       .

[11948 rows x 4 columns]